name: Demo 2
on:
  repository_dispatch:
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        repositories: ["openerp-atomfeed-service","odoo-modules","OpenELIS"]
    steps:
      - name: Print Message
        env:
          REPOSITORY_NAME: ${{ martix.repositories }}
        run: echo "hiiiiiii- ${REPOSITORY_NAME}"
