name: Demo 2
on:
  issues:
    types: [closed]
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "hiiiiiii- ${{ github.event.issue.assignees }}"
