name: Demo Flow
on:
  workflow_dispatch:
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        env:
          USERNAME: ${{ secrets.DEMO_SECRET }}
        run: echo "hiiiiiii ${USERNAME}"
      - name: Setup Java 7
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '7'
      - name: Trigger Demo 2
        run : apt-get install ant@1.9
