name: Demo Flow
on:
  workflow_dispatch:
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        env:
          USERNAME: ${{ secrets.DEMO_SECRET }}
        run: echo "hiiiiiii ${USERNAME}"
      - name: Setup Java 7
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '7'
      - name: Trigger Demo 2
        run : |
              java -version
              wget https://dlcdn.apache.org//ant/binaries/apache-ant-1.9.16-bin.tar.gz
              mkdir /tmp/ant
              tar -zxf apache-ant-1.9.16-bin.tar.gz --directory /tmp/ant
              ls /tmp/ant
              export ANT_HOME=/tmp/ant/apache-ant-1.9.16
              export PATH=$PATH:$ANT_HOME/bin
              which ant
              ant -version
